<Invader@Image>:
	source:'atlas://invasion/invader'
	size_hint:None,None
	size:40,40
<Shooter@Image>:
	source:'atlas://invasion/shooter'
	size_hint:None,None
	size:40,40
	pos:300,0
<Boom@Image>:
	source:'atlas://invasion/boom'
	size_hint:None,None
	size:26,30
<Shot@Ammo>:
	source:'atlas://invasion/shot'
	size_hint:None,None
	size:12,15

<Missile@Ammo>:
	source:'atlas://invasion/missile'
	size_hint:None,None
	size:12,27
	
	